TicketComment:
  type: object
  config:
    description: "A ticket comment"
    fields:
      id:
        type: "Int!"
        description: "The unique ID of the ticket."
      user:
        type: "User"
        description: "User, that created this ticket."
      comment:
        type: "String"
        description: "Reason of ticket."
